---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: master
rule_files:
- "/etc/prometheus/alerting-rules.yml"
scrape_configs:
- job_name: prometheus
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - localhost:9090
    labels:
      alias: Prometheus
- job_name: node
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - hv1:9100
    - docker02:9100
    labels:
      alias: Node
- job_name: snmp
  scrape_interval: 60s
  static_configs:
  - targets:
    - 192.168.1.232
  metrics_path: "/snmp"
  params:
    module:
    - synology
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: snmp-exporter:9116
alerting:
  alert_relabel_configs: []
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
